### ISSUE TITLE
Notes created on the A5X2 Manta don't open

### ISSUE THREAD

**Issue by oschl-git** [philips/supernote-obsidian-plugin#37]
Hi there,

I purchased the Manta and configured it to sync through Syncthing and my Obsidian Vault, which works very well. Unfortunately, the plugin doesn't seem to be able to open any of my notes. When I try to open a .note file, the tab immediately closes and Obsidian displays an error message: `Failed to open ""`.

This is my first Supernote device, so I have no experience prior to this. Maybe it could be because I am using Linux or missing some dependency on my computer?

I am attaching a test note that the plugin is failing to open.

Thanks!

[Broken note.zip](https://github.com/user-attachments/files/18186419/Broken.note.zip)

**Comment by oschl-git** [comment]
Tried testing this on my Android phone (Pixel 7) as well and the behaviour is unfortunately the same. The note doesn't open.

**Comment by philips** [comment]
Is this a note with no template or anything? Just an empty page?

**Comment by oschl-git** [comment]
Yes, no template. Blank page with a few words scribbled on it with the ink pen.

**Comment by philips** [comment]
supernote-tool also fails on this file.

```
(.venv) $ supernote-tool convert ~/supernote-typescript/tests/input/manta.note foo.png
Traceback (most recent call last):
  File "/Users/philips/supernote-tool/.venv/bin/supernote-tool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 224, in main
    args.handler(args)
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 121, in subcommand_convert
    if args.type == 'png': convert_to_png(args, notebook, palette)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 58, in convert_to_png
    img = converter.convert(args.number, visibility_overlay=vo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/converter.py", line 83, in convert
    converted_img = self._convert_layered_page(page, self.palette, visibility_overlay, highres_grayscale)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/converter.py", line 118, in _convert_layered_page
    img = self._create_image_from_decoder(decoder, binary, palette=plt, blank_hint=all_blank, horizontal=horizontal)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/converter.py", line 166, in _create_image_from_decoder
    bitmap, size, bpp = decoder.decode(binary, palette=palette, all_blank=blank_hint, horizontal=horizontal)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philips/supernote-tool/.venv/lib/python3.11/site-packages/supernotelib/decoder.py", line 186, in decode
    raise exceptions.DecoderException(f'uncompressed bitmap length = {len(uncompressed)}, expected = {expected_length}')
supernotelib.exceptions.DecoderException: uncompressed bitmap length = 4915200, expected = 2628288
```

**Comment by oschl-git** [comment]
Sounds like there are some software changes on the Manta with how the device saves notes, maybe? Should I submit an issue to that repository as well? I am not familiar with supernote-tool.

**Comment by philips** [comment]
@oschl-git I filed a bug over there too just as a friendly FYI

**Comment by oschl-git** [comment]
Awesome, thanks so much and for all your work on this plugin, I really appreciate it.

**Comment by philips** [comment]
Could you export a PDF or PNG of this note for my testing?

**Comment by oschl-git** [comment]
Sure thing, here you go.

[Broken.pdf](https://github.com/user-attachments/files/18186960/Broken.pdf)

**Comment by philips** [comment]
Thank you. Looks like the resolution increased quite a bit on notes. I don't know how to get this programmatically though.

```
--- a/src/parsing.ts
+++ b/src/parsing.ts
@@ -189,8 +189,8 @@ function uint8ArrayToString(
 export interface SupernoteX extends ISupernote {}
 export class SupernoteX {
        constructor(buffer: Uint8Array) {
-               this.pageWidth = 1404;
-               this.pageHeight = 1872;
+               this.pageWidth = 1920;
+               this.pageHeight = 2560;
                this.addressSize = 4;
                this.lengthFieldSize = 4;
                this.defaultLayers = ['MAINLAYER', 'LAYER1', 'LAYER2', 'LAYER3', 'BGLAYER'];
```

**Comment by philips** [comment]
I released 2.2.8 with this fixed. Thanks!

**Comment by oschl-git** [comment]
Fucking incredible dude, thanks so much. Will test when I get home.

**Comment by oschl-git** [comment]
Just confirming that everything is working flawlessly now, so cool, thanks again.
